export const dashboardData = [
    {
    name: "Last Week",
    "Active VMs": 1247,
    "Inactive VMs": 1253,
    "Active Network": 402,
    "Inactive Network": 198,
    },
    {
      name: "Monday",
    "Active VMs": 1258,
    "Inactive VMs": 1242,
    "Active Network": 221,
    "Inactive Network": 379,
    },
    {
      name: "Tuesday",
    "Active VMs": 1150,
    "Inactive VMs": 1350,
    "Active Network": 426,
    "Inactive Network": 174,
    },
    {
      name: "Wednesday",
    "Active VMs": 1240,
    "Inactive VMs": 1260,
    "Active Network": 475,
    "Inactive Network": 125,
    },
    {
      name: "Thursday",
    "Active VMs": 1250,
    "Inactive VMs": 1250,
    "Active Network": 218,
    "Inactive Network": 382,
    },
    {
      name: "Friday",
    "Active VMs": 1600,
    "Inactive VMs": 900,
    "Active Network": 296,
    "Inactive Network": 204,
    },
    {
        name: "Weekends",
    "Active VMs": 0,
    "Inactive VMs": 0,
    "Active Network": 0,
    "Inactive Network": 0,
      }
  ];
  
  export const userRows = [
    {
      id: 1,
      username: "Kristian Frank",
      email: "krfr04@school.edu",
      status: "Active",
      member: "Faculty",
    },
    {
      id: 2,
      username: "Gaia Rahman",
      email: "gara03@school.edu",
      status: "Active",
      member: "Faculty",
    },
    {
      id: 3,
      username: "Leighton Moran",
      email: "lemo09@email.school.edu",
      status: "Active",
      member: "Student",
    },
    {
      id: 4,
      username: "Zofia Peralta",
      email: "zope01@email.school.edu",
      status: "Deprecated",
      member: "Alumni",
    },
    {
      id: 5,
      username: "Jon Snow",
      email: "josn29@school.edu",
      status: "Active",
      member: "Faculty",
    },
    {
      id: 6,
      username: "Mali King",
      email: "maki09@email.school.edu",
      status: "Deprecated",
      member: "Alumni",
    },
    {
      id: 7,
      username: "Saskia Bonner",
      email: "sabo18@school.edu",
      status: "Compromised",
      member: "Faculty",
    },
    {
      id: 8,
      username: "Kadeem Washington",
      email: "kawa31@email.school.edu",
      status: "Active",
      member: "Student",
    },
    {
      id: 9,
      username: "Ronald Hagan",
      email: "Roha21@school.edu",
      status: "Compromised",
      member: "Faculty",
    },
    {
      id: 10,
      username: "Taha Martinez",
      email: "tama12@email.school.edu",
      status: "Compromised",
      member: "Student",
    },
  ];

  export const userLaptopRows = [
    {
      id: 1,
      username: "Kristian Frank",
      email: "krfr04@school.edu",
      status: "Active",
      model: "Model 3",
      member: "Faculty",
    },
    {
      id: 2,
      username: "Gaia Rahman",
      email: "gara03@school.edu",
      status: "Active",
      model: "Model 3",
      member: "Faculty",
    },
    {
      id: 3,
      username: "Leighton Moran",
      email: "lemo09@email.school.edu",
      status: "Missing",
      model: "Model 2",
      member: "Student",
    },
    {
      id: 4,
      username: "Zofia Peralta",
      email: "zope01@email.school.edu",
      status: "Loaned",
      model: "Model 2",
      member: "Student",
    },
    {
      id: 5,
      username: "Jon Snow",
      email: "josn29@school.edu",
      status: "Active",
      model: "Model 3",
      member: "Faculty",
    },
    {
      id: 6,
      username: "Mali King",
      email: "maki09@email.school.edu",
      model: "Model 2",
      status: "Loaned",
      member: "Student",
    },
    {
      id: 7,
      username: "Saskia Bonner",
      email: "sabo18@school.edu",
      status: "Damaged",
      model: "Model 3",
      member: "Faculty",
    },
    {
      id: 8,
      username: "Kadeem Washington",
      email: "kawa31@email.school.edu",
      status: "Damaged",
      model: "Model 2",
      member: "Student",
    },
    {
      id: 9,
      username: "Ronald Hagan",
      email: "Roha21@school.edu",
      model: "Model 3",
      status: "Active",
      member: "Faculty",
    },
    {
      id: 10,
      username: "Taha Martinez",
      email: "tama12@email.school.edu",
      model: "Model 2",
      status: "Loaned",
      member: "Student",
    },
  ];

  